# Generated by Django 3.1.2 on 2021-06-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210603_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='path',
            field=models.TextField(null=True),
        ),
    ]
